# Generated by Django 5.0.3 on 2026-06-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEvasao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_frequencia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Frequência')),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], max_length=10, verbose_name='Severidade')),
                ('data_alerta', models.DateTimeField(auto_now_add=True, verbose_name='Data do Alerta')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='alunos.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Alerta de Evasão',
                'verbose_name_plural': 'Alertas de Evasão',
                'ordering': ['-data_alerta'],
            },
        ),
    ]
